import { StyleSheet } from 'react-native';

export const colors = {
  bg: '#0f0f13',
  surface: '#13131a',
  border: '#1e1e2e',
  headerBorder: '#1e1e28',
  red: '#e63946',
  redDim: '#e6394618',
  redBorder: '#e6394630',
  redBg: '#1a0f10',
  redTextDim: '#664040',
  green: '#4caf50',
  greenBg: '#1a2e1a',
  greenBorder: '#2a4a2a',
  white: '#fff',
  muted: '#555',
  faint: '#444',
  navActive: '#1a1020',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },

  // Header
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 56,
    paddingBottom: 14,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.headerBorder,
    gap: 10,
  },
  logoDot: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: colors.red,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText: { flex: 1 },
  headerTitle: { color: colors.white, fontSize: 17, fontWeight: '600', letterSpacing: 0.5 },
  headerSub: { color: colors.muted, fontSize: 11, marginTop: 1 },
  livePill: {
    backgroundColor: colors.greenBg,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: colors.greenBorder,
  },
  liveText: { color: colors.green, fontSize: 11, fontWeight: '500' },

  // Camera
  cameraWrapper: {
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 20,
    overflow: 'hidden',
    height: 450,
    borderWidth: 1,
    borderColor: colors.border,
  },
  camera: { flex: 1 },
  corner: {
    position: 'absolute',
    width: 20,
    height: 20,
    borderColor: colors.red,
  },
  cornerTL: { top: 14, left: 14, borderTopWidth: 2, borderLeftWidth: 2, borderTopLeftRadius: 3 },
  cornerTR: { top: 14, right: 14, borderTopWidth: 2, borderRightWidth: 2, borderTopRightRadius: 3 },
  cornerBL: { bottom: 14, left: 14, borderBottomWidth: 2, borderLeftWidth: 2, borderBottomLeftRadius: 3 },
  cornerBR: { bottom: 14, right: 14, borderBottomWidth: 2, borderRightWidth: 2, borderBottomRightRadius: 3 },
  scanLabel: {
    position: 'absolute',
    bottom: 14,
    alignSelf: 'center',
    backgroundColor: 'rgba(230,57,70,0.15)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.redBorder,
  },
  scanText: { color: colors.red, fontSize: 11, fontWeight: '600', letterSpacing: 1 },

  // Stats
  statsRow: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginTop: 12,
    gap: 8,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.surface,
    borderWidth: 0.5,
    borderColor: colors.border,
    borderRadius: 14,
    padding: 12,
  },
  statLabel: { color: colors.muted, fontSize: 16, textTransform: 'uppercase', letterSpacing: 0.6, marginBottom: 4 },
  statValue: { color: colors.white, fontSize: 22, fontWeight: '600', lineHeight: 24 },
  statPercent: { color: colors.green, fontSize: 13 },
  statValueAlert: { color: colors.red },
  statUnit: { color: colors.faint, fontSize: 16, marginTop: 3 },

  // Alert bar
  alertBar: {
    marginHorizontal: 16,
    marginTop: 10,
    backgroundColor: colors.redBg,
    borderWidth: 1,
    borderColor: colors.redBorder,
    borderRadius: 14,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  alertIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: colors.redDim,
    alignItems: 'center',
    justifyContent: 'center',
  },
  alertTitle: { color: colors.red, fontSize: 12, fontWeight: '600' },
  alertSub: { color: colors.redTextDim, fontSize: 11, marginTop: 2 },

  // Bottom nav
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.bg,
    borderTopWidth: 0.5,
    borderTopColor: colors.headerBorder,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 10,
    paddingBottom: 28,
  },
  navBtn: {
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 20,
    paddingVertical: 4,
    borderRadius: 12,
  },
  navBtnActive: { backgroundColor: colors.navActive },
  navLabel: { fontSize: 10, color: colors.muted, letterSpacing: 0.3 },
  navLabelActive: { color: colors.red },

  // Permission screen
  permissionText: { textAlign: 'center', color: colors.white, marginBottom: 16 },

  // Modal
  modalOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'flex-end',
    zIndex: 100,
  },
  modalSheet: {
    marginTop: '40%',
    backgroundColor: '#13131a',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 0.5,
    borderColor: '#1e1e2e',
    padding: 20,
    paddingBottom: 40,
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#2a2a35',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '600',
    marginBottom: 4,
  },
  modalSub: {
    color: '#555',
    fontSize: 12,
    marginBottom: 16,
  },
  alarmCard: {
    backgroundColor: '#0f0f13',
    borderWidth: 0.5,
    borderColor: '#1e1e2e',
    borderRadius: 14,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    gap: 12,
  },
  alarmCardActive: {
    borderColor: '#e63946',
    backgroundColor: '#1a0f10',
  },
  alarmIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#1e1e2e',
    alignItems: 'center',
    justifyContent: 'center',
  },
  alarmIconBoxActive: {
    backgroundColor: '#e6394618',
  },
  alarmName: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
  },
  alarmDesc: {
    color: '#555',
    fontSize: 11,
    marginTop: 2,
  },
  alarmNameActive: {
    color: '#e63946',
  },
  alarmCheck: {
    marginLeft: 'auto',
  },
  volumeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 16,
    marginBottom: 4,
  },
  volumeLabel: {
    color: '#555',
    fontSize: 12,
    width: 56,
  },
  volumeTrack: {
    flex: 1,
    height: 4,
    backgroundColor: '#1e1e2e',
    borderRadius: 2,
  },
  volumeFill: {
    height: '100%',
    backgroundColor: '#e63946',
    borderRadius: 2,
  },
  testBtn: {
    marginTop: 16,
    backgroundColor: '#e6394618',
    borderWidth: 1,
    borderColor: '#e6394640',
    borderRadius: 14,
    padding: 14,
    alignItems: 'center',
  },
  testBtnText: {
    color: '#e63946',
    fontSize: 14,
    fontWeight: '600',
  },
  testBtnStop: {
    backgroundColor: '#e6394630',
    borderColor: '#e63946',
  },

  //Logs
  // Log Screen
logContainer: {
  flex: 1,
  paddingHorizontal: 16,
  paddingTop: 12,
},
summaryRow: {
  flexDirection: 'row' as const,
  gap: 10,
  marginBottom: 18,
},
summaryCard: {
  flex: 1,
  backgroundColor: '#111',
  borderRadius: 14,
  padding: 14,
  alignItems: 'center' as const,
  borderWidth: 0.5,
  borderColor: '#1e1e2e',
},
summaryValue: {
  fontSize: 26,
  fontWeight: '700' as const,
  color: '#fff',
},
summaryLabel: {
  fontSize: 12,
  color: '#666',
  marginTop: 4,
  textAlign: 'center' as const,
},
logSection: {
  marginBottom: 24,
},
sectionHeader: {
  flexDirection: 'row' as const,
  justifyContent: 'space-between' as const,
  alignItems: 'center' as const,
  marginBottom: 12,
},
sectionTitle: {
  fontSize: 17,
  fontWeight: '700' as const,
  color: '#fff',
  marginBottom: 12,
},
clearBtn: {
  fontSize: 13,
  color: '#e63946',
},
graphContainer: {
  flexDirection: 'row' as const,
  height: 210,
  backgroundColor: '#111',
  borderRadius: 16,
  padding: 12,
  borderWidth: 0.5,
  borderColor: '#1e1e2e',
},
yAxis: {
  justifyContent: 'space-between' as const,
  marginRight: 8,
  height: 160,
},
yLabel: {
  fontSize: 12,
  color: '#888',
  fontWeight: '500' as const,
},
barsArea: {
  flex: 1,
  position: 'relative' as const,
},
gridLine: {
  position: 'absolute' as const,
  left: 0,
  right: 0,
  height: 1,
  backgroundColor: '#222',
},
barsRow: {
  flexDirection: 'row' as const,
  alignItems: 'flex-end' as const,
  height: 160,
  gap: 6,
},
barWrapper: {
  flex: 1,
  alignItems: 'center' as const,
},
barBg: {
  width: '100%' as const,
  backgroundColor: '#1a1a1a',
  borderRadius: 4,
  justifyContent: 'flex-end' as const,
  overflow: 'hidden' as const,
},
bar: {
  width: '100%' as const,
  borderRadius: 4,
  minHeight: 2,
},
barScore: {
  fontSize: 10,
  color: '#aaa',
  marginTop: 3,
  fontWeight: '500' as const,
},
barLabel: {
  fontSize: 11,
  color: '#888',
  marginTop: 3,
  fontWeight: '500' as const,
},
barAlerts: {
  fontSize: 10,
  color: '#e63946',
  fontWeight: '600' as const,
},
legend: {
  flexDirection: 'row' as const,
  justifyContent: 'space-between' as const,
  marginTop: 14,
  backgroundColor: '#111',
  borderRadius: 12,
  padding: 12,
  borderWidth: 0.5,
  borderColor: '#1e1e2e',
},
legendItem: {
  alignItems: 'center' as const,
  gap: 4,
},
legendDot: {
  width: 12,
  height: 12,
  borderRadius: 6,
},
legendLabel: {
  fontSize: 13,
  color: '#fff',
  fontWeight: '600' as const,
},
legendRange: {
  fontSize: 11,
  color: '#666',
},
sessionCard: {
  flexDirection: 'row' as const,
  justifyContent: 'space-between' as const,
  alignItems: 'center' as const,
  backgroundColor: '#111',
  borderRadius: 14,
  padding: 16,
  marginBottom: 10,
  borderWidth: 0.5,
  borderColor: '#1e1e2e',
},
sessionLeft: {
  gap: 4,
  flex: 1,
},
sessionDate: {
  fontSize: 15,
  fontWeight: '700' as const,
  color: '#fff',
},
sessionTime: {
  fontSize: 13,
  color: '#777',
},
sessionMeta: {
  flexDirection: 'row' as const,
  gap: 8,
  marginTop: 6,
},
metaBadge: {
  backgroundColor: '#1e1e2e',
  borderRadius: 8,
  paddingHorizontal: 8,
  paddingVertical: 3,
},
metaBadgeText: {
  fontSize: 12,
  color: '#aaa',
  fontWeight: '500' as const,
},
sessionRight: {
  alignItems: 'center' as const,
  minWidth: 80,
},
sessionScore: {
  fontSize: 32,
  fontWeight: '800' as const,
},
sessionScoreLabel: {
  fontSize: 12,
  color: '#666',
  fontWeight: '500' as const,
  marginTop: 2,
},
emptyState: {
  alignItems: 'center' as const,
  paddingVertical: 48,
  gap: 10,
},
emptyText: {
  color: '#666',
  fontSize: 16,
  fontWeight: '600' as const,
},
emptySubText: {
  color: '#444',
  fontSize: 13,
  textAlign: 'center' as const,
  lineHeight: 20,
},

});