import { StyleSheet } from 'react-native';

export const colors = {
  bg: '#0f0f13',
  surface: '#13131a',
  border: '#1e1e2e',
  headerBorder: '#1e1e28',
  red: '#e63946',
  redDim: '#e6394618',
  redBorder: '#e6394630',
  redBg: '#1a0f10',
  redTextDim: '#664040',
  green: '#4caf50',
  greenBg: '#1a2e1a',
  greenBorder: '#2a4a2a',
  white: '#fff',
  muted: '#555',
  faint: '#444',
  navActive: '#1a1020',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },

  // Header
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 56,
    paddingBottom: 14,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.headerBorder,
    gap: 10,
  },
  logoDot: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: colors.red,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText: { flex: 1 },
  headerTitle: { color: colors.white, fontSize: 17, fontWeight: '600', letterSpacing: 0.5 },
  headerSub: { color: colors.muted, fontSize: 11, marginTop: 1 },
  livePill: {
    backgroundColor: colors.greenBg,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: colors.greenBorder,
  },
  liveText: { color: colors.green, fontSize: 11, fontWeight: '500' },

  // Camera
  cameraWrapper: {
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 20,
    overflow: 'hidden',
    height: 450,
    borderWidth: 1,
    borderColor: colors.border,
  },
  camera: { flex: 1 },
  corner: {
    position: 'absolute',
    width: 20,
    height: 20,
    borderColor: colors.red,
  },
  cornerTL: { top: 14, left: 14, borderTopWidth: 2, borderLeftWidth: 2, borderTopLeftRadius: 3 },
  cornerTR: { top: 14, right: 14, borderTopWidth: 2, borderRightWidth: 2, borderTopRightRadius: 3 },
  cornerBL: { bottom: 14, left: 14, borderBottomWidth: 2, borderLeftWidth: 2, borderBottomLeftRadius: 3 },
  cornerBR: { bottom: 14, right: 14, borderBottomWidth: 2, borderRightWidth: 2, borderBottomRightRadius: 3 },
  scanLabel: {
    position: 'absolute',
    bottom: 14,
    alignSelf: 'center',
    backgroundColor: 'rgba(230,57,70,0.15)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.redBorder,
  },
  scanText: { color: colors.red, fontSize: 11, fontWeight: '600', letterSpacing: 1 },

  // Stats
  statsRow: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginTop: 12,
    gap: 8,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.surface,
    borderWidth: 0.5,
    borderColor: colors.border,
    borderRadius: 14,
    padding: 12,
  },
  statLabel: { color: colors.muted, fontSize: 16, textTransform: 'uppercase', letterSpacing: 0.6, marginBottom: 4 },
  statValue: { color: colors.white, fontSize: 22, fontWeight: '600', lineHeight: 24 },
  statPercent: { color: colors.green, fontSize: 13 },
  statValueAlert: { color: colors.red },
  statUnit: { color: colors.faint, fontSize: 16, marginTop: 3 },

  // Alert bar
  alertBar: {
    marginHorizontal: 16,
    marginTop: 10,
    backgroundColor: colors.redBg,
    borderWidth: 1,
    borderColor: colors.redBorder,
    borderRadius: 14,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  alertIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: colors.redDim,
    alignItems: 'center',
    justifyContent: 'center',
  },
  alertTitle: { color: colors.red, fontSize: 12, fontWeight: '600' },
  alertSub: { color: colors.redTextDim, fontSize: 11, marginTop: 2 },

  // Bottom nav
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.bg,
    borderTopWidth: 0.5,
    borderTopColor: colors.headerBorder,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 10,
    paddingBottom: 28,
  },
  navBtn: {
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 20,
    paddingVertical: 4,
    borderRadius: 12,
  },
  navBtnActive: { backgroundColor: colors.navActive },
  navLabel: { fontSize: 10, color: colors.muted, letterSpacing: 0.3 },
  navLabelActive: { color: colors.red },

  // Permission screen
  permissionText: { textAlign: 'center', color: colors.white, marginBottom: 16 },

  // Modal
  modalOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'flex-end',
    zIndex: 100,
  },
  modalSheet: {
    marginTop: '40%',
    backgroundColor: '#13131a',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 0.5,
    borderColor: '#1e1e2e',
    padding: 20,
    paddingBottom: 40,
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#2a2a35',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '600',
    marginBottom: 4,
  },
  modalSub: {
    color: '#555',
    fontSize: 12,
    marginBottom: 16,
  },
  alarmCard: {
    backgroundColor: '#0f0f13',
    borderWidth: 0.5,
    borderColor: '#1e1e2e',
    borderRadius: 14,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    gap: 12,
  },
  alarmCardActive: {
    borderColor: '#e63946',
    backgroundColor: '#1a0f10',
  },
  alarmIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#1e1e2e',
    alignItems: 'center',
    justifyContent: 'center',
  },
  alarmIconBoxActive: {
    backgroundColor: '#e6394618',
  },
  alarmName: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
  },
  alarmDesc: {
    color: '#555',
    fontSize: 11,
    marginTop: 2,
  },
  alarmNameActive: {
    color: '#e63946',
  },
  alarmCheck: {
    marginLeft: 'auto',
  },
  volumeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 16,
    marginBottom: 4,
  },
  volumeLabel: {
    color: '#555',
    fontSize: 12,
    width: 56,
  },
  volumeTrack: {
    flex: 1,
    height: 4,
    backgroundColor: '#1e1e2e',
    borderRadius: 2,
  },
  volumeFill: {
    height: '100%',
    backgroundColor: '#e63946',
    borderRadius: 2,
  },
  testBtn: {
    marginTop: 16,
    backgroundColor: '#e6394618',
    borderWidth: 1,
    borderColor: '#e6394640',
    borderRadius: 14,
    padding: 14,
    alignItems: 'center',
  },
  testBtnText: {
    color: '#e63946',
    fontSize: 14,
    fontWeight: '600',
  },
  testBtnStop: {
    backgroundColor: '#e6394630',
    borderColor: '#e63946',
  },
});